// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/622023f642f9ab4cd6e060b2
###
GET http://localhost:8080/contacts/622023f642f9ab4cd6e060b3
###
GET http://localhost:8080/contacts/622023f642f9ab4cd6e060b4

// PRODUCTION Deploy
###
GET https://cse341-instructor.herokuapp.com/contacts
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3
###
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4
